export enum ErrorCode {
  CUSTOMER_ALREADY_HAS_CARD = 'CUSTOMER_ALREADY_HAS_CARD',
  IDEMPOTENCY_KEY_REQUIRED = 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_ALREADY_USED = 'IDEMPOTENCY_KEY_ALREADY_USED'
}

